{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "env0-agent.fullname" . }}
  labels:
    {{- include "env0-agent.labels" . | nindent 4 }}
rules:
  {{- if .Values.rbac.rules }}
  {{- toYaml .Values.rbac.rules | nindent 2 }}
  {{- else }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "env0-agent.fullname" . }}
  labels:
    {{- include "env0-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "env0-agent.fullname" .) .Values.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "env0-agent.fullname" . }}
{{- end }}
